name: hugeicons
description: "4,000+ Free Flutter Icons. Created by Hugeicons Pro Icon Library. Hugeicons Pro the most beautiful icon library for developers."
version: 0.0.7
homepage: https://hugeicons.com
repository: https://github.com/hugeicons/hugeicons-flutter
issue_tracker: https://github.com/hugeicons/hugeicons-flutter/issues
documentation: https://docs.hugeicons.com

environment:
  sdk: ">=2.18.6 <3.13.2"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: HgiStrokeRounded
      fonts:
        - asset: lib/fonts/hgi-stroke-rounded.ttf
